flyve-mdm/ios-inventory-library

FlyveMDMInventory/DeviceInventory.swift

This PR print XML skeleton
Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/11

Print XML skeleton

---

FlyveMDMInventory/DeviceInventory.swift
FlyveMDMInventory/FlyveMDMInventory.h
FlyveMDMInventoryTests/FlyveMDMInventoryTests.swift

This PR add documentation
Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/7

Write the documentation

---

FlyveMDMInventory.xcodeproj/project.pbxproj
FlyveMDMInventory/DeviceInventory.swift
FlyveMDMInventory/InventoryTask.swift

This PR create conventional names for the API client library
Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/19

Conventional names for the API client library cross platform

---

FlyveMDMInventory.podspec

This PR update podspec source for distribution
Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/10

Update podspec source for distribution

---

FlyveMDMInventory/InventoryTask.swift

This PR update XML Inventory
Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/2

Update XML Inventory

---

FlyveMDMInventory.podspec
FlyveMDMInventory/InventoryTask.swift

We are wainting feedback from @wawax to improve the XML output later.

Proposal of the version 1.1.0

---

CHANGELOG.md
FlyveMDMInventory.podspec
FlyveMDMInventory/InventoryTask.swift
package-lock.json
package.json

New version released https://github.com/flyve-mdm/flyve-mdm-ios-inventory/releases/tag/1.1.0

Update develop branch with release metada

---

CHANGELOG.md
FlyveMDMInventory.podspec
FlyveMDMInventory/InventoryTask.swift
package-lock.json
package.json

This PR Updates develop branch to new release (v1.1.0)
Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/releases/tag/1.1.0

Update to new release

---

Example/Example/Info.plist
Example/Podfile.lock
Example/Pods/Local Podspecs/FlyveMDMInventory.podspec.json
Example/Pods/Manifest.lock
Example/Pods/Target Support Files/FlyveMDMInventory/Info.plist
FlyveMDMInventory.xcodeproj/project.pbxproj
FlyveMDMInventory/Hardware.m
FlyveMDMInventory/OperatingSystem.m
FlyveMDMInventoryTests/BatteryTest.swift
FlyveMDMInventoryTests/CarrierTest.swift
FlyveMDMInventoryTests/CpuTest.swift
FlyveMDMInventoryTests/HardwareTest.swift
FlyveMDMInventoryTests/Info.plist
FlyveMDMInventoryTests/MemoryTest.swift
FlyveMDMInventoryTests/NetworkTest.swift
FlyveMDMInventoryTests/OperatingSystemTest.swift
FlyveMDMInventoryTests/StorageTest.swift

This PR creates unit test
Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/9

Create unit test

---

.swiftlint.yml
Example/Example/AppDelegate.swift
Example/Example/ViewController.swift
Example/ExampleTests/ExampleTests.swift
Example/ExampleUITests/ExampleUITests.swift
FlyveMDMInventory.xcodeproj/project.pbxproj
FlyveMDMInventory/InventoryTask.swift
FlyveMDMInventoryTests/BatteryTest.swift
FlyveMDMInventoryTests/CarrierTest.swift
FlyveMDMInventoryTests/CpuTest.swift
FlyveMDMInventoryTests/FlyveMDMInventoryTests.swift
FlyveMDMInventoryTests/HardwareTest.swift
FlyveMDMInventoryTests/MemoryTest.swift
FlyveMDMInventoryTests/NetworkTest.swift
FlyveMDMInventoryTests/OperatingSystemTest.swift
FlyveMDMInventoryTests/StorageTest.swift

This PR implements SwiftLint
Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/9

Implement SwiftLint

---

.travis.yml
scripts/push.sh

This PR execute automatic pod upload with Travis CI
Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/10

Automatic upload pod with Travis CI

---

package.json

* Add metadata from the `podspec.json` to the `package.json`
Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/38

Join format of podspec.json into package.json

---

README.md

* Markdown linting
* Add link of the wiki
* Add copying information
Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/3

README improves and linting

---

FlyveMDMInventory/InventoryTask.swift
FlyveMDMInventory/Storage.m

This PR fix inventory xml file
- date format
- show disk size in MB
- show disk size in drives
closed: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/49

Fix inventory

---

FlyveMDMInventoryTests/BatteryTest.swift
FlyveMDMInventoryTests/CarrierTest.swift
FlyveMDMInventoryTests/CpuTest.swift
FlyveMDMInventoryTests/FlyveMDMInventoryTests.swift
FlyveMDMInventoryTests/HardwareTest.swift
FlyveMDMInventoryTests/MemoryTest.swift
FlyveMDMInventoryTests/NetworkTest.swift
FlyveMDMInventoryTests/OperatingSystemTest.swift
FlyveMDMInventoryTests/StorageTest.swift

Hi, @hectorerb 
This PR in progress adds the documentation to all the Swift sources.

Code Documentation

---

README.md

Hi, @hectorerb 
I added some new badges and the contact information for the Telegram Dev Group.

README improves

---

ci/scripts/deploy_master.sh

Hi, @ajsb85 
This PR fix generate github release using [conventional-github-releaser](https://github.com/conventional-changelog/conventional-github-releaser)

Fix generate GitHub release 

---

Example/Example/AppDelegate.swift
Example/Example/ViewController.swift
Example/ExampleTests/ExampleTests.swift
Example/ExampleUITests/ExampleUITests.swift
ci/scripts/bundler_config.sh
ci/scripts/deploy_develop.sh
ci/scripts/deploy_master.sh
ci/scripts/fastlane_config.sh
ci/scripts/git_config.sh
ci/scripts/install.sh
ci/scripts/keychain_add.sh
ci/scripts/keychain_remove.sh
ci/scripts/pod_trunk_push.sh
ci/scripts/test.sh

Hi, @ajsb85 
This PR adds these changes:
- Fix CHANGELOG header
- Fix generate documentation with jazzy
close: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/76

Fix header CHANGELOG

---

Example/Example.xcodeproj/project.pbxproj
Example/Example/ViewController.swift
Example/Podfile.lock
Example/Pods/Local Podspecs/FlyveMDMInventory.podspec.json
Example/Pods/Manifest.lock
Example/Pods/Pods.xcodeproj/project.pbxproj
Example/Pods/Target Support Files/FlyveMDMInventory/FlyveMDMInventory-umbrella.h
Example/Pods/Target Support Files/FlyveMDMInventory/Info.plist
Example/Pods/Target Support Files/Pods-Example/Pods-Example-acknowledgements.markdown
Example/Pods/Target Support Files/Pods-Example/Pods-Example-acknowledgements.plist
Example/Pods/Target Support Files/Pods-Example/Pods-Example-frameworks.sh
Example/Pods/Target Support Files/Pods-Example/Pods-Example-resources.sh
Example/Pods/Target Support Files/Pods-ExampleTests/Pods-ExampleTests-frameworks.sh
Example/Pods/Target Support Files/Pods-ExampleTests/Pods-ExampleTests-resources.sh
Example/Pods/Target Support Files/Pods-ExampleUITests/Pods-ExampleUITests-frameworks.sh
Example/Pods/Target Support Files/Pods-ExampleUITests/Pods-ExampleUITests-resources.sh
FlyveMDMInventory/InventoryTask.swift
FlyveMDMInventory/XMLRead.swift

Hi, @ajsb85
This PR adds these changes:
- Reword keys to camelCase on JSON inventory
- Create an array of objects by each element on content tag
close: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/27

reword keys to camelCase on JSON inventory

---

FlyveMDMInventory/InventoryTask.swift

This PR works with:
- Improve labels on json with camelCase

Change json label

---

.jazzy.yaml
ci/scripts/deploy_develop.sh
circle.yml

Hi, @ajsb85 / @rafaelje 
This PR fix generate documentation

Fix generate documentation

---

ci/scripts/deploy_develop.sh
ci/scripts/deploy_master.sh

Hi, @ajsb85 / @rafaelje
This PR adds automatic update cache
ref: https://github.com/flyve-mdm/flyve-mdm-press-kit/issues/34

Automatic cache version

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/settings.yml

Hi, @ajsb85 / @hectorerb 
This PR adds the .github folder containing the templates for both issue and pull request and the yaml file for the bot settings

Add .github folder

---

.github/invite-contributors.yml
README.md

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] Other... Please describe:
```
Wrong license information: GNU GPL v3.0
- Correct information: Apache v2.0
- Config to automatically invite authors of merged pull requests
```
[ ] Yes
[X] No
```

[WIP] Update readme and config to invite-contributors

---

README.md

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] Other... Please describe:
```
Wrong license link: [GNU GPL v3](https://www.gnu.org/licenses/gpl-3.0.en.html)
Correct license link: [Apache License](http://www.apache.org/licenses/LICENSE-2.0)
```
[ ] Yes
[X] No
```

Change license link

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/invite-contributors.yml
CONTRIBUTING.md

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```
- Wrong usage to add team name
- Wrong links in contributing and pull request template
- Correct usage to add team name
- Correct links
- Minor style changes
```
[ ] Yes
[x] No
```

Update project documentation

---

.github/ISSUE_TEMPLATE.md
.github/settings.yml
CONTRIBUTING.md
README.md

The links of the repo name are out of date
The links in the build status section are out of date
The IRC link adds an square bracket at the end of #flyve-mdm
Issue # N/A
Links fixed

Change links in project documentation

---

_config.yml
_includes/header.html
_layouts/post.html
_posts/static/2017-10-05-how-it-works.md
_posts/static/2017-10-05-roadmap.md
_posts/static/2017-10-09-contributing.md
howtos/index.html
news.html

Issue #97 
The Documentation and Wiki sections were renamed to Development and How-tos respectively

How tos and Development sections

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

- The commit message follows our guidelines: [Conventional Commit](https://conventionalcommits.org/)
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)
Issue #N/A
New issue and PR template

New issue and PR templates

---

README.md

- The commit message follows our guidelines: [Conventional Commit](https://conventionalcommits.org/)
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)
Issue #92

Adds Greenkeeper badge

---

404.html
_posts/static/2017-10-09-contributing.md

Remove guidelines, redirect to project's contributing file and add assistance links
Closes #N/A

Change contributing article

---

CONTRIBUTING.md

update contributing guidelines to new format
Closes #N/A

Change contributing guidelines

---

.travis.yml
_posts/static/2018-05-10-how-to-translate.md

Add how to translate article
Closes #N/A

Add how to translate article

---

.github/PULL_REQUEST_TEMPLATE.md
.github/settings.yml
CONTRIBUTING.md

- PR template
add new references
add estimated time in pomodoros
- Contributing guidelines
add url to new issues
add missing command
- Settings
add cherry pick label
Closes #N/A

Update PR template & Contributing guidelines

---

ci/README.md

Add env variables and libraries used to run the ci
|Assignee|:tomato:|
|:---|:---:|
|@Naylin15 |2|
Closes #N/A
Related #N/A
Depends on #N/A

Update readme in ci folder

---

_posts/static/2017-10-09-contributing.md
_posts/static/2018-05-15-workflow.md

add command to import public key
add guide to add email
|Assignee|:tomato:|
|:---|:---:|
|@Naylin15 |1|
Closes #N/A
Related #N/A
Depends on #N/A

Add GPG steps
